<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25317" started-at="2021-12-13T16:10:15Z" finished-at="2021-12-13T16:10:41Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25317" started-at="2021-12-13T16:10:15Z" finished-at="2021-12-13T16:10:41Z">
      <class name="org.chetu.load.test.HdMeetLoadJitsi">
        <test-method status="FAIL" signature="hdmeetlogin()[pri:0, instance:org.chetu.load.test.HdMeetLoadJitsi@52bf72b5]" name="hdmeetlogin" duration-ms="25213" started-at="2021-12-13T21:40:16Z" finished-at="2021-12-13T21:40:41Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Cannot find elements when the XPath is null.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Cannot find elements when the XPath is null.at org.openqa.selenium.By$ByXPath.<init>(By.java:339)at org.openqa.selenium.By.xpath(By.java:92)at page.objects.PageObjectClass.getLoginButton(PageObjectClass.java:52)at org.chetu.load.test.functions.HDMeetFunctions.login(HDMeetFunctions.java:53)at org.chetu.load.test.HdMeetLoadJitsi.hdmeetlogin(HdMeetLoadJitsi.java:21)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hdmeetlogin -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:org.chetu.load.test.HdMeetLoadJitsi@52bf72b5]" name="afterMethod" is-config="true" duration-ms="15" started-at="2021-12-13T21:40:41Z" finished-at="2021-12-13T21:40:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=hdmeetlogin status=FAILURE method=HdMeetLoadJitsi.hdmeetlogin()[pri:0, instance:org.chetu.load.test.HdMeetLoadJitsi@52bf72b5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- org.chetu.load.test.HdMeetLoadJitsi -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
